#macro GLOW_TYPE_NONE 0
#macro GLOW_TYPE_NEON 1
#macro GLOW_TYPE_DISK 2
#macro SMOOTHING_RAPID 0
#macro SMOOTHING_GENTLE 1
#macro SMOOTHING_SINE 2
#macro SMOOTHING_RAPID2 3
#macro SMOOTHING_OPENEND 4

// LIGHTNINGMAKER DEFAULTS
	
#macro LMD_SEGMENT 12
#macro LMD_DENSITY .25
#macro LMD_HEIGHT 120
#macro LMD_SPD -.1
#macro LMD_TURBULENCE 3
#macro LMD_LINE_WIDTH 4
#macro LMD_COLOR #FFFFFF
#macro LMD_OUTLINE_WIDTH 5
#macro LMD_OUTLINE_COLOR #E90057
#macro LMD_SMOOTHING_TYPE SMOOTHING_GENTLE
#macro LMD_SEC_NOISE_STRENGTH .17
#macro LMD_SEC_NOISE_DENSITY_MULT 2

#macro LMD_CHILD_CHANCE .1
#macro LMD_CHILD_LIFE_MIN 6
#macro LMD_CHILD_LIFE_MAX 60
#macro LMD_CHILDREN_MAX 3
#macro LMD_CHILD_LENGTH_MIN 100
#macro LMD_CHILD_LENGTH_MAX infinity
#macro LMD_RECURSION_LEVEL_MAX 2
#macro LMD_CHILD_CUTOFF_START .0
#macro LMD_CHILD_CUTOFF_END .0
#macro LMD_FADE_OUT true
#macro LMD_FADE_IN false
#macro LMD_CHILD_REDUCE_WIDTH true
#macro LMD_CHILD_REDUCE_ALPHA false

#macro LMD_GLOW_TYPE GLOW_TYPE_DISK
#macro LMD_BLEND_MODE_ADD false
#macro LMD_NEON_GLOW_INTENSITY 1.9
#macro LMD_NEON_GLOW_INNER 13.7
#macro LMD_NEON_GLOW_INNER_MULT 21
#macro LMD_DISK_GLOW_RADIUS 256
#macro LMD_DISK_GLOW_QUALITY 5.5
#macro LMD_DISK_GLOW_INTENSITY 1
#macro LMD_DISK_GLOW_ALPHA 1
#macro LMD_DISK_GLOW_GAMMA .2
