#macro GLOW_TYPE_NONE 0
#macro GLOW_TYPE_NEON 1
#macro GLOW_TYPE_DISK 2
#macro SMOOTHING_RAPID 0
#macro SMOOTHING_GENTLE 1
#macro SMOOTHING_SINE 2
#macro SMOOTHING_RAPID2 3
#macro SMOOTHING_OPENEND 4

